digraph "unitGraph" {
    "r12 := @parameter0: java.lang.String[]"
    "r13 = null"
    "$r0 = new java.net.Socket"
    "specialinvoke $r0.<java.net.Socket: void <init>(java.lang.String,int)>(\"localhost\", 5006)"
    "r13 = $r0"
    "$r1 = new java.io.DataInputStream"
    "$r2 = virtualinvoke r13.<java.net.Socket: java.io.InputStream getInputStream()>()"
    "specialinvoke $r1.<java.io.DataInputStream: void <init>(java.io.InputStream)>($r2)"
    "r14 = $r1"
    "$r3 = <java.lang.System: java.io.PrintStream out>"
    "$r4 = virtualinvoke r14.<java.io.DataInputStream: java.lang.String readUTF()>()"
    "virtualinvoke $r3.<java.io.PrintStream: void println(java.lang.String)>($r4)"
    "goto [?= $r1 = new java.io.DataInputStream]"
    "$r11 := @caughtexception"
    "r15 = $r11"
    "virtualinvoke r15.<java.io.IOException: void printStackTrace()>()"
    "r16 = new java.lang.NullPointerException"
    "specialinvoke r16.<java.lang.NullPointerException: void <init>(java.lang.String)>(\"This statement would have triggered an Exception: virtualinvoke os.<java.io.DataOutputStream: void close()>()\")"
    "throw r16"
    "$r10 := @caughtexception"
    "virtualinvoke r13.<java.net.Socket: void close()>()"
    "goto [?= return]"
    "$r9 := @caughtexception"
    "$r8 := @caughtexception"
    "r6 = $r8"
    "r17 = new java.lang.NullPointerException"
    "specialinvoke r17.<java.lang.NullPointerException: void <init>(java.lang.String)>(\"This statement would have triggered an Exception: virtualinvoke os.<java.io.DataOutputStream: void close()>()\")"
    "throw r17"
    "$r7 := @caughtexception"
    "goto [?= throw r6]"
    "$r5 := @caughtexception"
    "throw r6"
    "return"
    "r12 := @parameter0: java.lang.String[]"->"r13 = null";
    "r13 = null"->"$r11 := @caughtexception";
    "r13 = null"->"$r8 := @caughtexception";
    "r13 = null"->"$r0 = new java.net.Socket";
    "$r0 = new java.net.Socket"->"$r11 := @caughtexception";
    "$r0 = new java.net.Socket"->"$r8 := @caughtexception";
    "$r0 = new java.net.Socket"->"specialinvoke $r0.<java.net.Socket: void <init>(java.lang.String,int)>(\"localhost\", 5006)";
    "specialinvoke $r0.<java.net.Socket: void <init>(java.lang.String,int)>(\"localhost\", 5006)"->"$r11 := @caughtexception";
    "specialinvoke $r0.<java.net.Socket: void <init>(java.lang.String,int)>(\"localhost\", 5006)"->"$r8 := @caughtexception";
    "specialinvoke $r0.<java.net.Socket: void <init>(java.lang.String,int)>(\"localhost\", 5006)"->"r13 = $r0";
    "r13 = $r0"->"$r11 := @caughtexception";
    "r13 = $r0"->"$r8 := @caughtexception";
    "r13 = $r0"->"$r1 = new java.io.DataInputStream";
    "$r1 = new java.io.DataInputStream"->"$r11 := @caughtexception";
    "$r1 = new java.io.DataInputStream"->"$r8 := @caughtexception";
    "$r1 = new java.io.DataInputStream"->"$r2 = virtualinvoke r13.<java.net.Socket: java.io.InputStream getInputStream()>()";
    "$r2 = virtualinvoke r13.<java.net.Socket: java.io.InputStream getInputStream()>()"->"$r11 := @caughtexception";
    "$r2 = virtualinvoke r13.<java.net.Socket: java.io.InputStream getInputStream()>()"->"$r8 := @caughtexception";
    "$r2 = virtualinvoke r13.<java.net.Socket: java.io.InputStream getInputStream()>()"->"specialinvoke $r1.<java.io.DataInputStream: void <init>(java.io.InputStream)>($r2)";
    "specialinvoke $r1.<java.io.DataInputStream: void <init>(java.io.InputStream)>($r2)"->"$r11 := @caughtexception";
    "specialinvoke $r1.<java.io.DataInputStream: void <init>(java.io.InputStream)>($r2)"->"$r8 := @caughtexception";
    "specialinvoke $r1.<java.io.DataInputStream: void <init>(java.io.InputStream)>($r2)"->"r14 = $r1";
    "r14 = $r1"->"$r11 := @caughtexception";
    "r14 = $r1"->"$r8 := @caughtexception";
    "r14 = $r1"->"$r3 = <java.lang.System: java.io.PrintStream out>";
    "$r3 = <java.lang.System: java.io.PrintStream out>"->"$r11 := @caughtexception";
    "$r3 = <java.lang.System: java.io.PrintStream out>"->"$r8 := @caughtexception";
    "$r3 = <java.lang.System: java.io.PrintStream out>"->"$r4 = virtualinvoke r14.<java.io.DataInputStream: java.lang.String readUTF()>()";
    "$r4 = virtualinvoke r14.<java.io.DataInputStream: java.lang.String readUTF()>()"->"$r11 := @caughtexception";
    "$r4 = virtualinvoke r14.<java.io.DataInputStream: java.lang.String readUTF()>()"->"$r8 := @caughtexception";
    "$r4 = virtualinvoke r14.<java.io.DataInputStream: java.lang.String readUTF()>()"->"virtualinvoke $r3.<java.io.PrintStream: void println(java.lang.String)>($r4)";
    "virtualinvoke $r3.<java.io.PrintStream: void println(java.lang.String)>($r4)"->"$r11 := @caughtexception";
    "virtualinvoke $r3.<java.io.PrintStream: void println(java.lang.String)>($r4)"->"$r8 := @caughtexception";
    "virtualinvoke $r3.<java.io.PrintStream: void println(java.lang.String)>($r4)"->"goto [?= $r1 = new java.io.DataInputStream]";
    "goto [?= $r1 = new java.io.DataInputStream]"->"$r11 := @caughtexception";
    "goto [?= $r1 = new java.io.DataInputStream]"->"$r8 := @caughtexception";
    "goto [?= $r1 = new java.io.DataInputStream]"->"$r1 = new java.io.DataInputStream";
    "$r11 := @caughtexception"->"r15 = $r11";
    "$r11 := @caughtexception"->"$r8 := @caughtexception";
    "r15 = $r11"->"virtualinvoke r15.<java.io.IOException: void printStackTrace()>()";
    "r15 = $r11"->"$r8 := @caughtexception";
    "virtualinvoke r15.<java.io.IOException: void printStackTrace()>()"->"$r10 := @caughtexception";
    "virtualinvoke r15.<java.io.IOException: void printStackTrace()>()"->"$r8 := @caughtexception";
    "virtualinvoke r15.<java.io.IOException: void printStackTrace()>()"->"r16 = new java.lang.NullPointerException";
    "r16 = new java.lang.NullPointerException"->"specialinvoke r16.<java.lang.NullPointerException: void <init>(java.lang.String)>(\"This statement would have triggered an Exception: virtualinvoke os.<java.io.DataOutputStream: void close()>()\")";
    "r16 = new java.lang.NullPointerException"->"$r10 := @caughtexception";
    "specialinvoke r16.<java.lang.NullPointerException: void <init>(java.lang.String)>(\"This statement would have triggered an Exception: virtualinvoke os.<java.io.DataOutputStream: void close()>()\")"->"throw r16";
    "specialinvoke r16.<java.lang.NullPointerException: void <init>(java.lang.String)>(\"This statement would have triggered an Exception: virtualinvoke os.<java.io.DataOutputStream: void close()>()\")"->"$r10 := @caughtexception";
    "throw r16"->"$r10 := @caughtexception";
    "$r10 := @caughtexception"->"virtualinvoke r13.<java.net.Socket: void close()>()";
    "$r10 := @caughtexception"->"$r9 := @caughtexception";
    "virtualinvoke r13.<java.net.Socket: void close()>()"->"goto [?= return]";
    "virtualinvoke r13.<java.net.Socket: void close()>()"->"$r9 := @caughtexception";
    "goto [?= return]"->"return";
    "$r9 := @caughtexception"->"goto [?= return]";
    "goto [?= return]"->"return";
    "$r8 := @caughtexception"->"r6 = $r8";
    "$r8 := @caughtexception"->"$r8 := @caughtexception";
    "r6 = $r8"->"$r7 := @caughtexception";
    "r6 = $r8"->"$r8 := @caughtexception";
    "r6 = $r8"->"r17 = new java.lang.NullPointerException";
    "r17 = new java.lang.NullPointerException"->"specialinvoke r17.<java.lang.NullPointerException: void <init>(java.lang.String)>(\"This statement would have triggered an Exception: virtualinvoke os.<java.io.DataOutputStream: void close()>()\")";
    "r17 = new java.lang.NullPointerException"->"$r7 := @caughtexception";
    "specialinvoke r17.<java.lang.NullPointerException: void <init>(java.lang.String)>(\"This statement would have triggered an Exception: virtualinvoke os.<java.io.DataOutputStream: void close()>()\")"->"throw r17";
    "specialinvoke r17.<java.lang.NullPointerException: void <init>(java.lang.String)>(\"This statement would have triggered an Exception: virtualinvoke os.<java.io.DataOutputStream: void close()>()\")"->"$r7 := @caughtexception";
    "throw r17"->"$r7 := @caughtexception";
    "$r7 := @caughtexception"->"virtualinvoke r13.<java.net.Socket: void close()>()";
    "$r7 := @caughtexception"->"$r5 := @caughtexception";
    "virtualinvoke r13.<java.net.Socket: void close()>()"->"goto [?= throw r6]";
    "virtualinvoke r13.<java.net.Socket: void close()>()"->"$r5 := @caughtexception";
    "goto [?= throw r6]"->"throw r6";
    "$r5 := @caughtexception"->"throw r6";
}
