digraph "unitGraph" {
    "r8 := @parameter0: java.lang.String[]"
    "$r0 = new compiler.c1.NullCheckTest$B"
    "specialinvoke $r0.<compiler.c1.NullCheckTest$B: void <init>()>()"
    "$r1 = new compiler.c1.NullCheckTest$A"
    "specialinvoke $r1.<compiler.c1.NullCheckTest$A: void <init>()>()"
    "staticinvoke <compiler.c1.NullCheckTest: void test(compiler.c1.NullCheckTest$A,compiler.c1.NullCheckTest$A)>(null, $r1)"
    "$r2 = new java.lang.InternalError"
    "specialinvoke $r2.<java.lang.InternalError: void <init>(java.lang.String)>(\"FAILURE: no exception\")"
    "throw $r2"
    "$r6 := @caughtexception"
    "$r7 = <java.lang.System: java.io.PrintStream out>"
    "virtualinvoke $r7.<java.io.PrintStream: void println(java.lang.String)>(\"CORRECT: NullPointerException\")"
    "goto [?= return]"
    "$r3 := @caughtexception"
    "r4 = $r3"
    "$r5 = <java.lang.System: java.io.PrintStream out>"
    "virtualinvoke $r5.<java.io.PrintStream: void println(java.lang.String)>(\"FAILURE: ClassCastException\")"
    "throw r4"
    "return"
    "r8 := @parameter0: java.lang.String[]"->"$r0 = new compiler.c1.NullCheckTest$B";
    "$r0 = new compiler.c1.NullCheckTest$B"->"specialinvoke $r0.<compiler.c1.NullCheckTest$B: void <init>()>()";
    "specialinvoke $r0.<compiler.c1.NullCheckTest$B: void <init>()>()"->"$r6 := @caughtexception";
    "specialinvoke $r0.<compiler.c1.NullCheckTest$B: void <init>()>()"->"$r3 := @caughtexception";
    "specialinvoke $r0.<compiler.c1.NullCheckTest$B: void <init>()>()"->"$r1 = new compiler.c1.NullCheckTest$A";
    "$r1 = new compiler.c1.NullCheckTest$A"->"$r6 := @caughtexception";
    "$r1 = new compiler.c1.NullCheckTest$A"->"$r3 := @caughtexception";
    "$r1 = new compiler.c1.NullCheckTest$A"->"specialinvoke $r1.<compiler.c1.NullCheckTest$A: void <init>()>()";
    "specialinvoke $r1.<compiler.c1.NullCheckTest$A: void <init>()>()"->"$r6 := @caughtexception";
    "specialinvoke $r1.<compiler.c1.NullCheckTest$A: void <init>()>()"->"$r3 := @caughtexception";
    "specialinvoke $r1.<compiler.c1.NullCheckTest$A: void <init>()>()"->"staticinvoke <compiler.c1.NullCheckTest: void test(compiler.c1.NullCheckTest$A,compiler.c1.NullCheckTest$A)>(null, $r1)";
    "staticinvoke <compiler.c1.NullCheckTest: void test(compiler.c1.NullCheckTest$A,compiler.c1.NullCheckTest$A)>(null, $r1)"->"$r6 := @caughtexception";
    "staticinvoke <compiler.c1.NullCheckTest: void test(compiler.c1.NullCheckTest$A,compiler.c1.NullCheckTest$A)>(null, $r1)"->"$r3 := @caughtexception";
    "staticinvoke <compiler.c1.NullCheckTest: void test(compiler.c1.NullCheckTest$A,compiler.c1.NullCheckTest$A)>(null, $r1)"->"$r2 = new java.lang.InternalError";
    "$r2 = new java.lang.InternalError"->"$r6 := @caughtexception";
    "$r2 = new java.lang.InternalError"->"$r3 := @caughtexception";
    "$r2 = new java.lang.InternalError"->"specialinvoke $r2.<java.lang.InternalError: void <init>(java.lang.String)>(\"FAILURE: no exception\")";
    "specialinvoke $r2.<java.lang.InternalError: void <init>(java.lang.String)>(\"FAILURE: no exception\")"->"$r6 := @caughtexception";
    "specialinvoke $r2.<java.lang.InternalError: void <init>(java.lang.String)>(\"FAILURE: no exception\")"->"$r3 := @caughtexception";
    "specialinvoke $r2.<java.lang.InternalError: void <init>(java.lang.String)>(\"FAILURE: no exception\")"->"throw $r2";
    "throw $r2"->"$r6 := @caughtexception";
    "throw $r2"->"$r3 := @caughtexception";
    "$r6 := @caughtexception"->"$r7 = <java.lang.System: java.io.PrintStream out>";
    "$r7 = <java.lang.System: java.io.PrintStream out>"->"virtualinvoke $r7.<java.io.PrintStream: void println(java.lang.String)>(\"CORRECT: NullPointerException\")";
    "virtualinvoke $r7.<java.io.PrintStream: void println(java.lang.String)>(\"CORRECT: NullPointerException\")"->"goto [?= return]";
    "goto [?= return]"->"return";
    "$r3 := @caughtexception"->"r4 = $r3";
    "r4 = $r3"->"$r5 = <java.lang.System: java.io.PrintStream out>";
    "$r5 = <java.lang.System: java.io.PrintStream out>"->"virtualinvoke $r5.<java.io.PrintStream: void println(java.lang.String)>(\"FAILURE: ClassCastException\")";
    "virtualinvoke $r5.<java.io.PrintStream: void println(java.lang.String)>(\"FAILURE: ClassCastException\")"->"throw r4";
}
