digraph "unitGraph" {
    "r16 := @parameter0: java.lang.String[]"
    "$r0 = new java.lang.StringBuffer"
    "specialinvoke $r0.<java.lang.StringBuffer: void <init>(java.lang.String)>(\"\")"
    "r1 = $r0"
    "$r2 = new java.lang.StringBuffer"
    "specialinvoke $r2.<java.lang.StringBuffer: void <init>(java.lang.String)>(\"Some test StringBuffer\")"
    "r3 = $r2"
    "$r4 = newarray (char)[5]"
    "virtualinvoke r1.<java.lang.StringBuffer: java.lang.StringBuffer insert(int,char[],int,int)>(0, $r4, 1, 2147483647)"
    "$r6 = new java.lang.RuntimeException"
    "specialinvoke $r6.<java.lang.RuntimeException: void <init>(java.lang.String)>(\"Exception expected\")"
    "throw $r6"
    "$r12 := @caughtexception"
    "r17 = $r12"
    "goto [?= $r13 = newarray (char)[25]]"
    "$r10 := @caughtexception"
    "r18 = $r10"
    "$r11 = new java.lang.RuntimeException"
    "specialinvoke $r11.<java.lang.RuntimeException: void <init>(java.lang.String)>(\"Wrong exception thrown.\")"
    "throw $r11"
    "$r13 = newarray (char)[25]"
    "virtualinvoke r3.<java.lang.StringBuffer: java.lang.StringBuffer insert(int,char[],int,int)>(2, $r13, 5, 2147483647)"
    "$r15 = new java.lang.RuntimeException"
    "specialinvoke $r15.<java.lang.RuntimeException: void <init>(java.lang.String)>(\"Exception expected\")"
    "throw $r15"
    "$r9 := @caughtexception"
    "r19 = $r9"
    "goto [?= return]"
    "$r7 := @caughtexception"
    "r20 = $r7"
    "$r8 = new java.lang.RuntimeException"
    "specialinvoke $r8.<java.lang.RuntimeException: void <init>(java.lang.String)>(\"Wrong exception thrown.\")"
    "throw $r8"
    "return"
    "r16 := @parameter0: java.lang.String[]"->"$r0 = new java.lang.StringBuffer";
    "$r0 = new java.lang.StringBuffer"->"specialinvoke $r0.<java.lang.StringBuffer: void <init>(java.lang.String)>(\"\")";
    "specialinvoke $r0.<java.lang.StringBuffer: void <init>(java.lang.String)>(\"\")"->"r1 = $r0";
    "r1 = $r0"->"$r2 = new java.lang.StringBuffer";
    "$r2 = new java.lang.StringBuffer"->"specialinvoke $r2.<java.lang.StringBuffer: void <init>(java.lang.String)>(\"Some test StringBuffer\")";
    "specialinvoke $r2.<java.lang.StringBuffer: void <init>(java.lang.String)>(\"Some test StringBuffer\")"->"r3 = $r2";
    "r3 = $r2"->"$r12 := @caughtexception";
    "r3 = $r2"->"$r10 := @caughtexception";
    "r3 = $r2"->"$r4 = newarray (char)[5]";
    "$r4 = newarray (char)[5]"->"$r12 := @caughtexception";
    "$r4 = newarray (char)[5]"->"$r10 := @caughtexception";
    "$r4 = newarray (char)[5]"->"virtualinvoke r1.<java.lang.StringBuffer: java.lang.StringBuffer insert(int,char[],int,int)>(0, $r4, 1, 2147483647)";
    "virtualinvoke r1.<java.lang.StringBuffer: java.lang.StringBuffer insert(int,char[],int,int)>(0, $r4, 1, 2147483647)"->"$r12 := @caughtexception";
    "virtualinvoke r1.<java.lang.StringBuffer: java.lang.StringBuffer insert(int,char[],int,int)>(0, $r4, 1, 2147483647)"->"$r10 := @caughtexception";
    "virtualinvoke r1.<java.lang.StringBuffer: java.lang.StringBuffer insert(int,char[],int,int)>(0, $r4, 1, 2147483647)"->"$r6 = new java.lang.RuntimeException";
    "$r6 = new java.lang.RuntimeException"->"$r12 := @caughtexception";
    "$r6 = new java.lang.RuntimeException"->"$r10 := @caughtexception";
    "$r6 = new java.lang.RuntimeException"->"specialinvoke $r6.<java.lang.RuntimeException: void <init>(java.lang.String)>(\"Exception expected\")";
    "specialinvoke $r6.<java.lang.RuntimeException: void <init>(java.lang.String)>(\"Exception expected\")"->"$r12 := @caughtexception";
    "specialinvoke $r6.<java.lang.RuntimeException: void <init>(java.lang.String)>(\"Exception expected\")"->"$r10 := @caughtexception";
    "specialinvoke $r6.<java.lang.RuntimeException: void <init>(java.lang.String)>(\"Exception expected\")"->"throw $r6";
    "throw $r6"->"$r12 := @caughtexception";
    "throw $r6"->"$r10 := @caughtexception";
    "$r12 := @caughtexception"->"r17 = $r12";
    "r17 = $r12"->"goto [?= $r13 = newarray (char)[25]]";
    "goto [?= $r13 = newarray (char)[25]]"->"$r9 := @caughtexception";
    "goto [?= $r13 = newarray (char)[25]]"->"$r7 := @caughtexception";
    "goto [?= $r13 = newarray (char)[25]]"->"$r13 = newarray (char)[25]";
    "$r10 := @caughtexception"->"r18 = $r10";
    "r18 = $r10"->"$r11 = new java.lang.RuntimeException";
    "$r11 = new java.lang.RuntimeException"->"specialinvoke $r11.<java.lang.RuntimeException: void <init>(java.lang.String)>(\"Wrong exception thrown.\")";
    "specialinvoke $r11.<java.lang.RuntimeException: void <init>(java.lang.String)>(\"Wrong exception thrown.\")"->"throw $r11";
    "$r13 = newarray (char)[25]"->"$r9 := @caughtexception";
    "$r13 = newarray (char)[25]"->"$r7 := @caughtexception";
    "$r13 = newarray (char)[25]"->"virtualinvoke r3.<java.lang.StringBuffer: java.lang.StringBuffer insert(int,char[],int,int)>(2, $r13, 5, 2147483647)";
    "virtualinvoke r3.<java.lang.StringBuffer: java.lang.StringBuffer insert(int,char[],int,int)>(2, $r13, 5, 2147483647)"->"$r9 := @caughtexception";
    "virtualinvoke r3.<java.lang.StringBuffer: java.lang.StringBuffer insert(int,char[],int,int)>(2, $r13, 5, 2147483647)"->"$r7 := @caughtexception";
    "virtualinvoke r3.<java.lang.StringBuffer: java.lang.StringBuffer insert(int,char[],int,int)>(2, $r13, 5, 2147483647)"->"$r15 = new java.lang.RuntimeException";
    "$r15 = new java.lang.RuntimeException"->"$r9 := @caughtexception";
    "$r15 = new java.lang.RuntimeException"->"$r7 := @caughtexception";
    "$r15 = new java.lang.RuntimeException"->"specialinvoke $r15.<java.lang.RuntimeException: void <init>(java.lang.String)>(\"Exception expected\")";
    "specialinvoke $r15.<java.lang.RuntimeException: void <init>(java.lang.String)>(\"Exception expected\")"->"$r9 := @caughtexception";
    "specialinvoke $r15.<java.lang.RuntimeException: void <init>(java.lang.String)>(\"Exception expected\")"->"$r7 := @caughtexception";
    "specialinvoke $r15.<java.lang.RuntimeException: void <init>(java.lang.String)>(\"Exception expected\")"->"throw $r15";
    "throw $r15"->"$r9 := @caughtexception";
    "throw $r15"->"$r7 := @caughtexception";
    "$r9 := @caughtexception"->"r19 = $r9";
    "r19 = $r9"->"goto [?= return]";
    "goto [?= return]"->"return";
    "$r7 := @caughtexception"->"r20 = $r7";
    "r20 = $r7"->"$r8 = new java.lang.RuntimeException";
    "$r8 = new java.lang.RuntimeException"->"specialinvoke $r8.<java.lang.RuntimeException: void <init>(java.lang.String)>(\"Wrong exception thrown.\")";
    "specialinvoke $r8.<java.lang.RuntimeException: void <init>(java.lang.String)>(\"Wrong exception thrown.\")"->"throw $r8";
}
