digraph "unitGraph" {
    "r3 := @parameter0: java.lang.Object"
    "$r0 = new java.io.ByteArrayOutputStream"
    "specialinvoke $r0.<java.io.ByteArrayOutputStream: void <init>()>()"
    "r7 = $r0"
    "$r1 = new java.io.ObjectOutputStream"
    "specialinvoke $r1.<java.io.ObjectOutputStream: void <init>(java.io.OutputStream)>(r7)"
    "r2 = $r1"
    "virtualinvoke r2.<java.io.ObjectOutputStream: void writeObject(java.lang.Object)>(r3)"
    "virtualinvoke r2.<java.io.ObjectOutputStream: void flush()>()"
    "virtualinvoke r2.<java.io.ObjectOutputStream: void close()>()"
    "$r4 = virtualinvoke r7.<java.io.ByteArrayOutputStream: byte[] toByteArray()>()"
    "return $r4"
    "$r5 := @caughtexception"
    "r8 = $r5"
    "$r6 = new java.lang.Error"
    "specialinvoke $r6.<java.lang.Error: void <init>(java.lang.Throwable)>(r8)"
    "throw $r6"
    "r3 := @parameter0: java.lang.Object"->"$r0 = new java.io.ByteArrayOutputStream";
    "r3 := @parameter0: java.lang.Object"->"$r5 := @caughtexception";
    "$r0 = new java.io.ByteArrayOutputStream"->"specialinvoke $r0.<java.io.ByteArrayOutputStream: void <init>()>()";
    "$r0 = new java.io.ByteArrayOutputStream"->"$r5 := @caughtexception";
    "specialinvoke $r0.<java.io.ByteArrayOutputStream: void <init>()>()"->"r7 = $r0";
    "specialinvoke $r0.<java.io.ByteArrayOutputStream: void <init>()>()"->"$r5 := @caughtexception";
    "r7 = $r0"->"$r1 = new java.io.ObjectOutputStream";
    "r7 = $r0"->"$r5 := @caughtexception";
    "$r1 = new java.io.ObjectOutputStream"->"specialinvoke $r1.<java.io.ObjectOutputStream: void <init>(java.io.OutputStream)>(r7)";
    "$r1 = new java.io.ObjectOutputStream"->"$r5 := @caughtexception";
    "specialinvoke $r1.<java.io.ObjectOutputStream: void <init>(java.io.OutputStream)>(r7)"->"r2 = $r1";
    "specialinvoke $r1.<java.io.ObjectOutputStream: void <init>(java.io.OutputStream)>(r7)"->"$r5 := @caughtexception";
    "r2 = $r1"->"virtualinvoke r2.<java.io.ObjectOutputStream: void writeObject(java.lang.Object)>(r3)";
    "r2 = $r1"->"$r5 := @caughtexception";
    "virtualinvoke r2.<java.io.ObjectOutputStream: void writeObject(java.lang.Object)>(r3)"->"virtualinvoke r2.<java.io.ObjectOutputStream: void flush()>()";
    "virtualinvoke r2.<java.io.ObjectOutputStream: void writeObject(java.lang.Object)>(r3)"->"$r5 := @caughtexception";
    "virtualinvoke r2.<java.io.ObjectOutputStream: void flush()>()"->"virtualinvoke r2.<java.io.ObjectOutputStream: void close()>()";
    "virtualinvoke r2.<java.io.ObjectOutputStream: void flush()>()"->"$r5 := @caughtexception";
    "virtualinvoke r2.<java.io.ObjectOutputStream: void close()>()"->"$r4 = virtualinvoke r7.<java.io.ByteArrayOutputStream: byte[] toByteArray()>()";
    "virtualinvoke r2.<java.io.ObjectOutputStream: void close()>()"->"$r5 := @caughtexception";
    "$r4 = virtualinvoke r7.<java.io.ByteArrayOutputStream: byte[] toByteArray()>()"->"return $r4";
    "$r4 = virtualinvoke r7.<java.io.ByteArrayOutputStream: byte[] toByteArray()>()"->"$r5 := @caughtexception";
    "$r5 := @caughtexception"->"r8 = $r5";
    "r8 = $r5"->"$r6 = new java.lang.Error";
    "$r6 = new java.lang.Error"->"specialinvoke $r6.<java.lang.Error: void <init>(java.lang.Throwable)>(r8)";
    "specialinvoke $r6.<java.lang.Error: void <init>(java.lang.Throwable)>(r8)"->"throw $r6";
}
