digraph "unitGraph" {
    "r11 := @parameter0: java.lang.String[]"
    "$r0 = new java.net.InetSocketAddress"
    "specialinvoke $r0.<java.net.InetSocketAddress: void <init>(java.lang.String,int)>(\"nosuchhostname\", 5182)"
    "r1 = $r0"
    "r12 = staticinvoke <java.nio.channels.SocketChannel: java.nio.channels.SocketChannel open()>()"
    "$r2 = virtualinvoke r12.<java.nio.channels.SocketChannel: java.net.Socket socket()>()"
    "virtualinvoke $r2.<java.net.Socket: void connect(java.net.SocketAddress,int)>(r1, 30000)"
    "$r3 = new java.lang.RuntimeException"
    "specialinvoke $r3.<java.lang.RuntimeException: void <init>(java.lang.String)>(\"Expected exception not thrown\")"
    "throw $r3"
    "$r5 := @caughtexception"
    "r13 = $r5"
    "r14 = staticinvoke <java.nio.channels.SocketChannel: java.nio.channels.SocketChannel open()>()"
    "$r6 = virtualinvoke r14.<java.nio.channels.SocketChannel: java.net.Socket socket()>()"
    "$r7 = new java.net.InetSocketAddress"
    "specialinvoke $r7.<java.net.InetSocketAddress: void <init>(int)>(0)"
    "virtualinvoke $r6.<java.net.Socket: void bind(java.net.SocketAddress)>($r7)"
    "$r8 = virtualinvoke r14.<java.nio.channels.SocketChannel: java.net.Socket socket()>()"
    "$r9 = new java.net.InetSocketAddress"
    "specialinvoke $r9.<java.net.InetSocketAddress: void <init>(int)>(0)"
    "virtualinvoke $r8.<java.net.Socket: void bind(java.net.SocketAddress)>($r9)"
    "$r10 = new java.lang.RuntimeException"
    "specialinvoke $r10.<java.lang.RuntimeException: void <init>(java.lang.String)>(\"Expected exception not thrown\")"
    "throw $r10"
    "$r4 := @caughtexception"
    "r15 = $r4"
    "return"
    "r11 := @parameter0: java.lang.String[]"->"$r0 = new java.net.InetSocketAddress";
    "$r0 = new java.net.InetSocketAddress"->"specialinvoke $r0.<java.net.InetSocketAddress: void <init>(java.lang.String,int)>(\"nosuchhostname\", 5182)";
    "specialinvoke $r0.<java.net.InetSocketAddress: void <init>(java.lang.String,int)>(\"nosuchhostname\", 5182)"->"r1 = $r0";
    "r1 = $r0"->"r12 = staticinvoke <java.nio.channels.SocketChannel: java.nio.channels.SocketChannel open()>()";
    "r1 = $r0"->"$r5 := @caughtexception";
    "r12 = staticinvoke <java.nio.channels.SocketChannel: java.nio.channels.SocketChannel open()>()"->"$r2 = virtualinvoke r12.<java.nio.channels.SocketChannel: java.net.Socket socket()>()";
    "r12 = staticinvoke <java.nio.channels.SocketChannel: java.nio.channels.SocketChannel open()>()"->"$r5 := @caughtexception";
    "$r2 = virtualinvoke r12.<java.nio.channels.SocketChannel: java.net.Socket socket()>()"->"virtualinvoke $r2.<java.net.Socket: void connect(java.net.SocketAddress,int)>(r1, 30000)";
    "$r2 = virtualinvoke r12.<java.nio.channels.SocketChannel: java.net.Socket socket()>()"->"$r5 := @caughtexception";
    "virtualinvoke $r2.<java.net.Socket: void connect(java.net.SocketAddress,int)>(r1, 30000)"->"$r3 = new java.lang.RuntimeException";
    "virtualinvoke $r2.<java.net.Socket: void connect(java.net.SocketAddress,int)>(r1, 30000)"->"$r5 := @caughtexception";
    "$r3 = new java.lang.RuntimeException"->"specialinvoke $r3.<java.lang.RuntimeException: void <init>(java.lang.String)>(\"Expected exception not thrown\")";
    "$r3 = new java.lang.RuntimeException"->"$r5 := @caughtexception";
    "specialinvoke $r3.<java.lang.RuntimeException: void <init>(java.lang.String)>(\"Expected exception not thrown\")"->"throw $r3";
    "specialinvoke $r3.<java.lang.RuntimeException: void <init>(java.lang.String)>(\"Expected exception not thrown\")"->"$r5 := @caughtexception";
    "throw $r3"->"$r5 := @caughtexception";
    "$r5 := @caughtexception"->"r13 = $r5";
    "r13 = $r5"->"r14 = staticinvoke <java.nio.channels.SocketChannel: java.nio.channels.SocketChannel open()>()";
    "r13 = $r5"->"$r4 := @caughtexception";
    "r14 = staticinvoke <java.nio.channels.SocketChannel: java.nio.channels.SocketChannel open()>()"->"$r6 = virtualinvoke r14.<java.nio.channels.SocketChannel: java.net.Socket socket()>()";
    "r14 = staticinvoke <java.nio.channels.SocketChannel: java.nio.channels.SocketChannel open()>()"->"$r4 := @caughtexception";
    "$r6 = virtualinvoke r14.<java.nio.channels.SocketChannel: java.net.Socket socket()>()"->"$r7 = new java.net.InetSocketAddress";
    "$r6 = virtualinvoke r14.<java.nio.channels.SocketChannel: java.net.Socket socket()>()"->"$r4 := @caughtexception";
    "$r7 = new java.net.InetSocketAddress"->"specialinvoke $r7.<java.net.InetSocketAddress: void <init>(int)>(0)";
    "$r7 = new java.net.InetSocketAddress"->"$r4 := @caughtexception";
    "specialinvoke $r7.<java.net.InetSocketAddress: void <init>(int)>(0)"->"virtualinvoke $r6.<java.net.Socket: void bind(java.net.SocketAddress)>($r7)";
    "specialinvoke $r7.<java.net.InetSocketAddress: void <init>(int)>(0)"->"$r4 := @caughtexception";
    "virtualinvoke $r6.<java.net.Socket: void bind(java.net.SocketAddress)>($r7)"->"$r8 = virtualinvoke r14.<java.nio.channels.SocketChannel: java.net.Socket socket()>()";
    "virtualinvoke $r6.<java.net.Socket: void bind(java.net.SocketAddress)>($r7)"->"$r4 := @caughtexception";
    "$r8 = virtualinvoke r14.<java.nio.channels.SocketChannel: java.net.Socket socket()>()"->"$r9 = new java.net.InetSocketAddress";
    "$r8 = virtualinvoke r14.<java.nio.channels.SocketChannel: java.net.Socket socket()>()"->"$r4 := @caughtexception";
    "$r9 = new java.net.InetSocketAddress"->"specialinvoke $r9.<java.net.InetSocketAddress: void <init>(int)>(0)";
    "$r9 = new java.net.InetSocketAddress"->"$r4 := @caughtexception";
    "specialinvoke $r9.<java.net.InetSocketAddress: void <init>(int)>(0)"->"virtualinvoke $r8.<java.net.Socket: void bind(java.net.SocketAddress)>($r9)";
    "specialinvoke $r9.<java.net.InetSocketAddress: void <init>(int)>(0)"->"$r4 := @caughtexception";
    "virtualinvoke $r8.<java.net.Socket: void bind(java.net.SocketAddress)>($r9)"->"$r10 = new java.lang.RuntimeException";
    "virtualinvoke $r8.<java.net.Socket: void bind(java.net.SocketAddress)>($r9)"->"$r4 := @caughtexception";
    "$r10 = new java.lang.RuntimeException"->"specialinvoke $r10.<java.lang.RuntimeException: void <init>(java.lang.String)>(\"Expected exception not thrown\")";
    "$r10 = new java.lang.RuntimeException"->"$r4 := @caughtexception";
    "specialinvoke $r10.<java.lang.RuntimeException: void <init>(java.lang.String)>(\"Expected exception not thrown\")"->"throw $r10";
    "specialinvoke $r10.<java.lang.RuntimeException: void <init>(java.lang.String)>(\"Expected exception not thrown\")"->"$r4 := @caughtexception";
    "throw $r10"->"$r4 := @caughtexception";
    "$r4 := @caughtexception"->"r15 = $r4";
    "r15 = $r4"->"return";
}
