digraph "unitGraph" {
    "$r0 = new java.nio.file.DirectoryIteratorException"
    "specialinvoke $r0.<java.nio.file.DirectoryIteratorException: void <init>(java.io.IOException)>(null)"
    "$r1 = new java.lang.RuntimeException"
    "specialinvoke $r1.<java.lang.RuntimeException: void <init>(java.lang.String)>(\"NullPointerException expected\")"
    "throw $r1"
    "$r8 := @caughtexception"
    "r18 = $r8"
    "$r9 = new java.nio.file.DirectoryIteratorException"
    "$r10 = new java.io.IOException"
    "specialinvoke $r10.<java.io.IOException: void <init>()>()"
    "specialinvoke $r9.<java.nio.file.DirectoryIteratorException: void <init>(java.io.IOException)>($r10)"
    "r19 = $r9"
    "$r11 = staticinvoke <javaT.nio.file.etc.Exceptions: byte[] serialize(java.lang.Object)>(r19)"
    "$r12 = staticinvoke <javaT.nio.file.etc.Exceptions: java.lang.Object deserialize(byte[])>($r11)"
    "r20 = (java.nio.file.DirectoryIteratorException) $r12"
    "r13 = virtualinvoke r20.<java.nio.file.DirectoryIteratorException: java.io.IOException getCause()>()"
    "if r13 != null goto staticinvoke <javaT.nio.file.etc.Exceptions: void hackCause(java.lang.Throwable,java.lang.Throwable)>(r20, null)"
    "$r17 = new java.lang.RuntimeException"
    "specialinvoke $r17.<java.lang.RuntimeException: void <init>(java.lang.String)>(\"Cause should not be null\")"
    "throw $r17"
    "staticinvoke <javaT.nio.file.etc.Exceptions: void hackCause(java.lang.Throwable,java.lang.Throwable)>(r20, null)"
    "$r14 = staticinvoke <javaT.nio.file.etc.Exceptions: byte[] serialize(java.lang.Object)>(r20)"
    "staticinvoke <javaT.nio.file.etc.Exceptions: java.lang.Object deserialize(byte[])>($r14)"
    "$r16 = new java.lang.RuntimeException"
    "specialinvoke $r16.<java.lang.RuntimeException: void <init>(java.lang.String)>(\"InvalidObjectException expected\")"
    "throw $r16"
    "$r3 := @caughtexception"
    "r21 = $r3"
    "$r4 = new java.lang.RuntimeException"
    "specialinvoke $r4.<java.lang.RuntimeException: void <init>()>()"
    "staticinvoke <javaT.nio.file.etc.Exceptions: void hackCause(java.lang.Throwable,java.lang.Throwable)>(r20, $r4)"
    "$r5 = staticinvoke <javaT.nio.file.etc.Exceptions: byte[] serialize(java.lang.Object)>(r20)"
    "staticinvoke <javaT.nio.file.etc.Exceptions: java.lang.Object deserialize(byte[])>($r5)"
    "$r7 = new java.lang.RuntimeException"
    "specialinvoke $r7.<java.lang.RuntimeException: void <init>(java.lang.String)>(\"InvalidObjectException expected\")"
    "throw $r7"
    "$r2 := @caughtexception"
    "r22 = $r2"
    "return"
    "$r0 = new java.nio.file.DirectoryIteratorException"->"specialinvoke $r0.<java.nio.file.DirectoryIteratorException: void <init>(java.io.IOException)>(null)";
    "$r0 = new java.nio.file.DirectoryIteratorException"->"$r8 := @caughtexception";
    "specialinvoke $r0.<java.nio.file.DirectoryIteratorException: void <init>(java.io.IOException)>(null)"->"$r1 = new java.lang.RuntimeException";
    "specialinvoke $r0.<java.nio.file.DirectoryIteratorException: void <init>(java.io.IOException)>(null)"->"$r8 := @caughtexception";
    "$r1 = new java.lang.RuntimeException"->"specialinvoke $r1.<java.lang.RuntimeException: void <init>(java.lang.String)>(\"NullPointerException expected\")";
    "$r1 = new java.lang.RuntimeException"->"$r8 := @caughtexception";
    "specialinvoke $r1.<java.lang.RuntimeException: void <init>(java.lang.String)>(\"NullPointerException expected\")"->"throw $r1";
    "specialinvoke $r1.<java.lang.RuntimeException: void <init>(java.lang.String)>(\"NullPointerException expected\")"->"$r8 := @caughtexception";
    "throw $r1"->"$r8 := @caughtexception";
    "$r8 := @caughtexception"->"r18 = $r8";
    "r18 = $r8"->"$r9 = new java.nio.file.DirectoryIteratorException";
    "$r9 = new java.nio.file.DirectoryIteratorException"->"$r10 = new java.io.IOException";
    "$r10 = new java.io.IOException"->"specialinvoke $r10.<java.io.IOException: void <init>()>()";
    "specialinvoke $r10.<java.io.IOException: void <init>()>()"->"specialinvoke $r9.<java.nio.file.DirectoryIteratorException: void <init>(java.io.IOException)>($r10)";
    "specialinvoke $r9.<java.nio.file.DirectoryIteratorException: void <init>(java.io.IOException)>($r10)"->"r19 = $r9";
    "r19 = $r9"->"$r11 = staticinvoke <javaT.nio.file.etc.Exceptions: byte[] serialize(java.lang.Object)>(r19)";
    "$r11 = staticinvoke <javaT.nio.file.etc.Exceptions: byte[] serialize(java.lang.Object)>(r19)"->"$r12 = staticinvoke <javaT.nio.file.etc.Exceptions: java.lang.Object deserialize(byte[])>($r11)";
    "$r12 = staticinvoke <javaT.nio.file.etc.Exceptions: java.lang.Object deserialize(byte[])>($r11)"->"r20 = (java.nio.file.DirectoryIteratorException) $r12";
    "r20 = (java.nio.file.DirectoryIteratorException) $r12"->"r13 = virtualinvoke r20.<java.nio.file.DirectoryIteratorException: java.io.IOException getCause()>()";
    "r13 = virtualinvoke r20.<java.nio.file.DirectoryIteratorException: java.io.IOException getCause()>()"->"if r13 != null goto staticinvoke <javaT.nio.file.etc.Exceptions: void hackCause(java.lang.Throwable,java.lang.Throwable)>(r20, null)";
    "if r13 != null goto staticinvoke <javaT.nio.file.etc.Exceptions: void hackCause(java.lang.Throwable,java.lang.Throwable)>(r20, null)"->"$r17 = new java.lang.RuntimeException";
    "if r13 != null goto staticinvoke <javaT.nio.file.etc.Exceptions: void hackCause(java.lang.Throwable,java.lang.Throwable)>(r20, null)"->"staticinvoke <javaT.nio.file.etc.Exceptions: void hackCause(java.lang.Throwable,java.lang.Throwable)>(r20, null)";
    "$r17 = new java.lang.RuntimeException"->"specialinvoke $r17.<java.lang.RuntimeException: void <init>(java.lang.String)>(\"Cause should not be null\")";
    "specialinvoke $r17.<java.lang.RuntimeException: void <init>(java.lang.String)>(\"Cause should not be null\")"->"throw $r17";
    "staticinvoke <javaT.nio.file.etc.Exceptions: void hackCause(java.lang.Throwable,java.lang.Throwable)>(r20, null)"->"$r14 = staticinvoke <javaT.nio.file.etc.Exceptions: byte[] serialize(java.lang.Object)>(r20)";
    "staticinvoke <javaT.nio.file.etc.Exceptions: void hackCause(java.lang.Throwable,java.lang.Throwable)>(r20, null)"->"$r3 := @caughtexception";
    "$r14 = staticinvoke <javaT.nio.file.etc.Exceptions: byte[] serialize(java.lang.Object)>(r20)"->"staticinvoke <javaT.nio.file.etc.Exceptions: java.lang.Object deserialize(byte[])>($r14)";
    "$r14 = staticinvoke <javaT.nio.file.etc.Exceptions: byte[] serialize(java.lang.Object)>(r20)"->"$r3 := @caughtexception";
    "staticinvoke <javaT.nio.file.etc.Exceptions: java.lang.Object deserialize(byte[])>($r14)"->"$r16 = new java.lang.RuntimeException";
    "staticinvoke <javaT.nio.file.etc.Exceptions: java.lang.Object deserialize(byte[])>($r14)"->"$r3 := @caughtexception";
    "$r16 = new java.lang.RuntimeException"->"specialinvoke $r16.<java.lang.RuntimeException: void <init>(java.lang.String)>(\"InvalidObjectException expected\")";
    "$r16 = new java.lang.RuntimeException"->"$r3 := @caughtexception";
    "specialinvoke $r16.<java.lang.RuntimeException: void <init>(java.lang.String)>(\"InvalidObjectException expected\")"->"throw $r16";
    "specialinvoke $r16.<java.lang.RuntimeException: void <init>(java.lang.String)>(\"InvalidObjectException expected\")"->"$r3 := @caughtexception";
    "throw $r16"->"$r3 := @caughtexception";
    "$r3 := @caughtexception"->"r21 = $r3";
    "r21 = $r3"->"$r4 = new java.lang.RuntimeException";
    "$r4 = new java.lang.RuntimeException"->"specialinvoke $r4.<java.lang.RuntimeException: void <init>()>()";
    "specialinvoke $r4.<java.lang.RuntimeException: void <init>()>()"->"staticinvoke <javaT.nio.file.etc.Exceptions: void hackCause(java.lang.Throwable,java.lang.Throwable)>(r20, $r4)";
    "staticinvoke <javaT.nio.file.etc.Exceptions: void hackCause(java.lang.Throwable,java.lang.Throwable)>(r20, $r4)"->"$r5 = staticinvoke <javaT.nio.file.etc.Exceptions: byte[] serialize(java.lang.Object)>(r20)";
    "staticinvoke <javaT.nio.file.etc.Exceptions: void hackCause(java.lang.Throwable,java.lang.Throwable)>(r20, $r4)"->"$r2 := @caughtexception";
    "$r5 = staticinvoke <javaT.nio.file.etc.Exceptions: byte[] serialize(java.lang.Object)>(r20)"->"staticinvoke <javaT.nio.file.etc.Exceptions: java.lang.Object deserialize(byte[])>($r5)";
    "$r5 = staticinvoke <javaT.nio.file.etc.Exceptions: byte[] serialize(java.lang.Object)>(r20)"->"$r2 := @caughtexception";
    "staticinvoke <javaT.nio.file.etc.Exceptions: java.lang.Object deserialize(byte[])>($r5)"->"$r7 = new java.lang.RuntimeException";
    "staticinvoke <javaT.nio.file.etc.Exceptions: java.lang.Object deserialize(byte[])>($r5)"->"$r2 := @caughtexception";
    "$r7 = new java.lang.RuntimeException"->"specialinvoke $r7.<java.lang.RuntimeException: void <init>(java.lang.String)>(\"InvalidObjectException expected\")";
    "$r7 = new java.lang.RuntimeException"->"$r2 := @caughtexception";
    "specialinvoke $r7.<java.lang.RuntimeException: void <init>(java.lang.String)>(\"InvalidObjectException expected\")"->"throw $r7";
    "specialinvoke $r7.<java.lang.RuntimeException: void <init>(java.lang.String)>(\"InvalidObjectException expected\")"->"$r2 := @caughtexception";
    "throw $r7"->"$r2 := @caughtexception";
    "$r2 := @caughtexception"->"r22 = $r2";
    "r22 = $r2"->"return";
}
